# Cluster-specific values for theia-prod.
# Purpose: AMD64 BuildKit runner scale sets for EduIDE and ls1intum.

global:
  storageClass: "csi-rbd-sc"
  nodeSelector:
    kubernetes.io/arch: amd64

createNamespaces: false

ghaArcScaleSetStatelessAmdEduide:
  enabled: false

ghaArcScaleSetStatelessArmEduide:
  enabled: false

ghaArcScaleSetAmdEduide:
  enabled: true
  runnerScaleSetName: "arc-buildkit-eduide-amd64"

ghaArcScaleSetAmdLs1intum:
  enabled: true
  runnerScaleSetName: "arc-buildkit-ls1intum-amd64"

ghaArcScaleSetArmEduide:
  enabled: false

ghaArcScaleSetArmLs1intum:
  enabled: false
