{{- if .Values.arcController.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: arc-systems
  labels:
    {{- include "theia-arc-bundle.labels" . | nindent 4 }}
{{- end }}
{{- if or .Values.arcRunners.enabled .Values.arcRunnersArm.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-runners
  labels:
    {{- include "theia-arc-bundle.labels" . | nindent 4 }}
{{- end }}
