apiVersion: v1
kind: Namespace
metadata:
  name: arc-systems
  labels:
    {{- include "theia-arc-bundle.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-runners
  labels:
    {{- include "theia-arc-bundle.labels" . | nindent 4 }}
